### ISSUE TITLE
The height of menu is calculated incorrectly with extra css

### ISSUE THREAD

**Issue by kylephp** [snapappointments/bootstrap-select#2229]
Hi @caseyjhol,
I want to add some custom styling on `<li>` (padding + border) but I found the height of inner menu will be calculated incorrectly and the scroll therefore will not be working properly.
JSfiddle: https://jsfiddle.net/mugncLhe/1/
When you use arrow down key to go down, the option 9  + 10 is not visible and the scroll is not updated.
Any idea how can I do it in the proper way?
TIA

**Comment by caseyjhol** [comment]
I'd recommend not applying any styling on the `li` element directly - although that should probably be taken into account when calculating size in bootstrap-select.

Using

```css
.dropdown-menu>li>a {
    padding: 5px 20px;
    border-bottom: 1px dotted #ccc;
}
```
should give you better results.

https://jsfiddle.net/caseyjhol/s1nLuz0x/
