### ISSUE TITLE
filter-option display:inline, width:auto

### ISSUE THREAD

**Issue by bazineta** [snapappointments/bootstrap-select#2261]
Noticed the following in the CSS:
```css
.filter-option {
  position: static;
  display: inline;
  padding: 0;
  width: auto;
}
```
Admittedly, CSS is not just my favorite thing ever, emergency dentistry being considerably higher on the list.

However, seems as if something can be display:inline, or have a width, but not both.
