### ISSUE TITLE
Change background color of seleted option

### ISSUE THREAD

**Issue by lcsqlpete** [snapappointments/bootstrap-select#2423]
How can I change the background color of the selected item in a single choice select?

**Comment by caseyjhol** [comment]
It depends on what version of Bootstrap you're using, but this can be done easily with CSS.

Bootstrap 3:
```css
.dropdown-menu>.active>a,
.dropdown-menu>.active>a:focus,
.dropdown-menu>.active>a:hover {
    background-color: red;
}
```
Bootstrap 4:
```css
.dropdown-item.active {
    background-color: red;
}
```
