### ISSUE TITLE
Bootstrap 3 w/ form-control Disabled Select 

### ISSUE THREAD

**Issue by kev22257** [snapappointments/bootstrap-select#2475]
When a select is disabled and you are using Bootstrap 3 and you have style blank and styleBase set to form-control as is suggested in the [documentation](https://developer.snapappointments.com/bootstrap-select/options/) when the drop down is disabled it does not visually APPEAR disabled (the mouse over works, but it's not grayed out).  I think this is because BS 3 styles btn:disabled and BS4 styles btn-*:disabled and btn is lost when styleBase is set to form-control.

https://plnkr.co/edit/M4Tkg3pvoBqsT7mQ

Setting style to "btn btn-default" solves the problem.  I think either the documentation needs to be updated for BS3 or the btn class should actually be put on the control in style and not in styleBase?

Thanks,

Kevin

**Comment by tiesont** [comment]
I've found copying the disabled styles from `.btn` also works:

```css
.dropdown-toggle.disabled,
.dropdown-toggle[disabled]
{
    cursor: not-allowed;
    filter: alpha(opacity=65);
    opacity: 0.65;
    -webkit-box-shadow: none;
    box-shadow: none;
}
```

Obviously this would select _any_ disabled dropdown button, but for my use case, that's a good thing.
