### ISSUE TITLE
HTML in multipleSeparator

### ISSUE THREAD

**Issue by Lothilarid** [snapappointments/bootstrap-select#2477]
Hello,

I try to customize my select with multipleSeparator: I need to display each selected option on a new line.

This is what I need: 
![option2](https://user-images.githubusercontent.com/4586661/83860895-2c2a8e80-a720-11ea-9a52-cef9ba0f2242.png)

And this is what I get when setting multipleSeparator = "&lt;br&gt;":
![option1](https://user-images.githubusercontent.com/4586661/83860965-495f5d00-a720-11ea-9753-24cc3b53cbec.png)

Do you know how I can do that ?
Thanks

**Comment by caseyjhol** [comment]
A workaround:

```html
<select class="selectpicker" multiple data-multiple-separator="&#10;" data-display="static">
</select>
```

```css
.bootstrap-select .dropdown-toggle .filter-option-inner-inner {
    white-space: pre-line;
}
```

https://plnkr.co/edit/iOiSMdiqXFpREI2m
