### ISSUE TITLE
 If the screen size is less than 992px, the menu is visible. If it is larger than that, the menu is not visible.

### ISSUE THREAD

**Issue by devplayg** [snapappointments/bootstrap-select#2493]
https://plnkr.co/edit/zlgq0bTQhMKslSyW?preview

Bootstrap version: 4.3.1
Bootstrap select version: 1.13.14
OS: Windows
Browser: Chrome, MS Edge
![bug](https://user-images.githubusercontent.com/10455627/85925514-d044c700-b8d3-11ea-995c-72130349389e.png)

**Comment by caseyjhol** [comment]
This is because of app.bundle.css:

```css
.dropdown-menu .dropdown-menu {
    visibility: hidden;
}
```
`.dropdown-menu` is hidden by default.
