### ISSUE TITLE
selectpicker fire change event with space in name

### ISSUE THREAD

**Issue by kimyoungjin06** [snapappointments/bootstrap-select#2545]
A bug is a _demonstrable problem_ that is caused by the code in the repository.

Guidelines for bug reports:

1. **Use the GitHub issue search.** Check if the issue has already been
   reported.

2. **Check if the issue has been fixed.** Try to reproduce it using the
   latest `master` or development branch in the repository.

3. **Provide environment details.** Provide your operating system, browser(s),
   jQuery version, Bootstrap version, and bootstrap-select version.

4. **Create an isolated and reproducible test case.** Create a reduced test
   case and include a link to a live example. Use [this Plunker debugging template](https://developer.snapappointments.com/bootstrap-select/playground/) to share your isolated test cases.

## Problem

- The selectpicker fire change event return value with space in the name is returned separated head part.
  - Example: original value: 'Dental caries' > firing return value: 'Dental'

### Additional problem

- Only one selectpicker call returns a selectpicker and separated search button.

#### HTML

```html
<!DOCTYPE html>
<html>

<head>
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>Disease Drug Protein Potential Relationship based on machine learning analysis</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <link rel="stylesheet" type="text/css" href="vendor/css/jquery.dataTables.min.css">
    <link rel="stylesheet" type="text/css" href="vendor/css/responsive.dataTables.min.css">
    <link rel="stylesheet" type="text/css" href="css/main.css">

    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.1.0/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">

    <script src='vendor/js/jquery-3.3.1.min.js'></script>
    <script src="vendor/js/jquery.dataTables.js"></script>
    <script src="vendor/js/dataTables.responsive.min.js"></script>
    <script src="vendor/js/dataTables.buttons.min.js"></script>
    <script src="vendor/js/buttons.html5.min.js"></script>
    <script src="js/main.js"></script>
    
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.1.0/js/bootstrap.bundle.min.js"></script>
    <script src="js/bootstrap-select.js"></script>
    
</head>

<body>
    <div class="wrap">
        <h4>Disease-Drug-Protein potential relationship based on Machine Learning Analysis</h4>
        <text>This Disease-Drug-Protein potential relationship is exported from Word Embedding model with PubMed 10 Years (2010~2019).</text>
    </div>
    <div class="wrap">
        <h6>Diseases, Drugs and Proteins</h6>
        <div class="container-wrapper">
            <label>Diseases</label>
            <select class="selectpicker form-control" id="Diseases-sp" data-live-search="true" title="Select a disease" data-size="5"></select>

            <label>Drugs</label>
            <select class="selectpicker form-control" id="Drugs-sp" data-container="body" data-live-search="true" title="Select a drug" data-hide-disabled="true" data-size="5"></select>

            <label>Proteins</label>
            <select class="selectpicker form-control" id="Proteins-sp" data-container="body" data-live-search="true" title="Select a protein" data-hide-disabled="true" data-size="5"></select>
        </div>
    </div>
</body>

</html>
```

#### Jquery, **main.js**

```js
$(document).ready(function () {

    $.fn.dataTable.ext.search.push(
        function(settings, data, dataIndex){
            var min = Date.parse($('#fromDate').val());
            var max = Date.parse($('#toDate').val());
            var targetDate = Date.parse(data[5]);

            if( (isNaN(min) && isNaN(max) ) || 
                (isNaN(min) && targetDate <= max )|| 
                ( min <= targetDate && isNaN(max) ) ||
                ( targetDate >= min && targetDate <= max) ){ 
                    return true;
            }
            return false;
        }
    )

    
// Get json data
    
function loadSelectItems(select, items) {
    var options = '';
    $.each(items, function(key, value) {
        options += '<option value=' + value.disease + '>' + value.disease + '</option>';
    });
    select.empty();
    select.append(options);
    select.selectpicker('refresh');
}
    
function get_drugs(select, items) {
    var options = '';
    $.each(items, function(key, value) {
        options += '<option value=' + value.drug + '>' + value.drug +', '+ value.PA +' ' + value.corr + '</option>';
    });
    select.empty();
    select.append(options);
    select.selectpicker('refresh');
}
const url = './disease.json';
$.getJSON(url, function (items) {loadSelectItems($('#Diseases-sp'), items)});
    
// Action for select disease
$(function() {
    $('#Diseases-sp').on("changed.bs.select", function(e, clickedIndex) {
        const drug_json = './json/drug/drugs_"' + this.value + '".json';
        $.getJSON(drug_json, function (items) {get_drugs($('#Drugs-sp'), items)});  
    });
});

});
```

#### css

```css
/* CUSTOM STYLE */

@import url(//fonts.googleapis.com/earlyaccess/jejugothic.css);

body,
select,
input {
    font-family: 'Jeju Gothic', sans-serif;
}

.wrap {
    width: 80%;
    margin: 50px auto;
}

.container {
  position: relative;
  display:table;
  background: red;
  width:100%;
  height: 100%; /* auto is default, you can have ur height here */
}

.container-wrapper {
  display: table-cell;
  margin:auto;
  text-align:center;
  font-size:0;
  width:90%;
  height:90%;
  vertical-align:middle;
}

.card {
  display: inline-block;
  height:50%;
  width:30%;
  border: 1px solid #ddd;
  background: #eee;
  margin:10px;
}
```

## Example

- [example github pages](https://kimyoungjin06.github.io/ddppr/)
