### ISSUE TITLE
When clicked, the select menu does not come out, until up or down arrow is pressed.

### ISSUE THREAD

**Issue by nikolaynikolaev013** [snapappointments/bootstrap-select#2664]
Hello there!

I'm using a normal select menu in an asp.net project. For example that one: 
```
<div class="form-group">
                            <label asp-for="CliendId"></label>
                            <select asp-for="CliendId" asp-items="availableClients" data-live-search="true" class="selectpicker form-control">
                            </select>
                            <span asp-validation-for="CliendId" class="text-danger"></span>
                        </div>
                        
```
<img width="400" alt="Screenshot 2021-10-02 at 22 05 20" src="https://user-images.githubusercontent.com/34801284/135728989-386944b4-86cc-44a2-8be7-d552e8f4da84.png">

And when I click it, it gets that blue frame, like it is marked:

<img width="408" alt="Screenshot 2021-10-02 at 22 03 12" src="https://user-images.githubusercontent.com/34801284/135729004-f6b9f0ec-de57-4bbc-8398-f47b883fc012.png">
And when I press the up or down arrow, it starts working properly:
<img width="423" alt="Screenshot 2021-10-02 at 22 03 30" src="https://user-images.githubusercontent.com/34801284/135729025-e085220c-9ce8-43da-bdf4-87a7a4b1be06.png">

The bootstrap theme I'm using is that one: [https://bootswatch.com/solar/](url)  - v5.1.1
Do you have any ideas where the problem can be? 

Thank you very much in advance! :)

**Comment by tophackr** [comment]
add this in you css
```css
.bootstrap-select .dropdown-toggle:focus,
.bootstrap-select > select.mobile-device:focus+.dropdown-toggle {
    outline: 0px auto -webkit-focus-ring-color !important;
}
```
