### ISSUE TITLE
Checked icon in RTL is displayed inward (RTL)

### ISSUE THREAD

**Issue by Skrypt** [snapappointments/bootstrap-select#2737]
As you can see here by doing a Google search we can see that the "checked" icon should not be reversed like it is currently.

https://www.bing.com/images/search?q=%D8%A7%D8%B4%D8%A7%D8%B1%D8%A9+%D8%B5%D8%AD&go=Search&qs=ds&form=QBIR&first=1&tsc=ImageHoverTitle

Here is how it is currently displayed : 

![image](https://user-images.githubusercontent.com/3228637/165991523-b50817f1-9761-439f-a2b9-e96a98f24000.png)

Here is how it should be displayed : 

![image](https://user-images.githubusercontent.com/3228637/165991450-76e3ac83-72d6-4c59-8839-e084eac970a3.png)

Here is the CSS that we used to "patch" the issue with an override : 

```css
html[dir="rtl"] .bootstrap-select .bs-ok-default:after
{
    border-width: 0 0.26em 0.26em 0 !important;
    transform: rotate(45deg) !important;
}
```
